version: '3.3'

networks:
  nw_prognimak: {}

services:
### Backend
  ordermanager:
    depends_on:
    - postgres
    environment:
      DB_NAME: test_db
      DB_PORT: 5432
      DB_HOST: postgres
      REPORTS_PATH: /var/ordermanager/reports
    hostname: ordermanager
    image: prognimak.ordermanager/backend:001
    networks:
      nw_prognimak: null
    ports:
    - 8083:8083
    volumes:
      - vol-ordermanager:/data/ordermanager-backend
      - ./backend/opt/reports:/var/ordermanager/reports:rw
 #### Volumes
volumes:

  vol-ordermanager: {}