apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanager-ui
  template:
    metadata:
      labels:
        app: ordermanager-ui
    spec:
      containers:
      - name: ordermanager-ui
        image: imageresources1prognimak.azurecr.io/ordermanager-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ordermanager-ui
    k8s-app: ordermanager-ui
  name: ordermanager-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: ordermanager-ui
