version: '3.3'

networks:
  nw_prognimak: {}

services:
### DB Postgres
  postgres:
    environment:
      PGDATA: /var/lib/postgresql-ftu/data/pgdata
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    hostname: postgres
    image: library/postgres:11
    networks:
      nw_prognimak: null
    ports:
    - 5455:5432
    volumes:
    - vol-postgres2:/var/lib/postgresql-ftu/data/pgdata:rw
    - ./backend/opt/sql/create-db:/docker-entrypoint-initdb.d:rw
### Backend
  ordermanager:
    depends_on:
    - postgres
    environment:
      DB_NAME: test_db
      DB_PORT: 5432
      DB_HOST: postgres
      REPORTS_PATH: /var/ordermanager/reports
    hostname: ordermanager
    image: prognimak.ordermanager/backend:003
    networks:
      nw_prognimak: null
    ports:
    - 8083:8083
    volumes:
      - ./backend/opt/reports:/var/ordermanager/reports:rw
##### UI
  ordermanager-ui:
    depends_on:
    - postgres
    - ordermanager
    hostname: ordermanager-ui
    image: prognimak.ordermanager/frontend
    networks:
      nw_prognimak: null
    ports:
      - 8082:8082
 #### Volumes
volumes:
  vol-postgres2: {}
  vol-ordermanager: {}